/**
 * GENERATED by scripts/sync-extracted.mjs — content extracted from the original
 * macos27 bundle. Edit /tmp/extracted/*.json + re-run the script instead of editing.
 * Source: photos.json
 */
export const photosSeed = [
  {
    "id": "p1",
    "fsId": "seed-photo-1",
    "name": "photo-1.svg",
    "url": "/macos27/photo-1.svg",
    "takenAt": "2026-07-14T17:42:00",
    "favorite": false,
    "deleted": false,
    "edited": false,
    "w": 1600,
    "h": 1067
  },
  {
    "id": "p2",
    "fsId": "seed-photo-2",
    "name": "photo-2.svg",
    "url": "/macos27/photo-2.svg",
    "takenAt": "2026-07-09T09:15:00",
    "favorite": true,
    "deleted": false,
    "edited": false,
    "w": 1600,
    "h": 1067
  },
  {
    "id": "p3",
    "fsId": "seed-photo-3",
    "name": "photo-3.svg",
    "url": "/macos27/photo-3.svg",
    "takenAt": "2026-06-21T08:03:00",
    "favorite": false,
    "deleted": false,
    "edited": false,
    "w": 1600,
    "h": 1067
  },
  {
    "id": "p4",
    "fsId": "seed-photo-4",
    "name": "photo-4.svg",
    "url": "/macos27/photo-4.svg",
    "takenAt": "2026-06-08T19:26:00",
    "favorite": false,
    "deleted": false,
    "edited": false,
    "w": 1600,
    "h": 1067
  },
  {
    "id": "p5",
    "fsId": "seed-photo-5",
    "name": "photo-5.svg",
    "url": "/macos27/photo-5.svg",
    "takenAt": "2026-06-02T20:11:00",
    "favorite": false,
    "deleted": false,
    "edited": false,
    "w": 1600,
    "h": 1067
  },
  {
    "id": "p6",
    "fsId": "seed-photo-6",
    "name": "photo-6.svg",
    "url": "/macos27/photo-6.svg",
    "takenAt": "2026-05-24T12:37:00",
    "favorite": false,
    "deleted": false,
    "edited": false,
    "w": 1600,
    "h": 1067
  },
  {
    "id": "p7",
    "fsId": "seed-photo-7",
    "name": "photo-7.svg",
    "url": "/macos27/photo-7.svg",
    "takenAt": "2026-05-11T21:58:00",
    "favorite": false,
    "deleted": false,
    "edited": false,
    "w": 1600,
    "h": 1067
  },
  {
    "id": "p8",
    "fsId": "seed-photo-8",
    "name": "photo-8.svg",
    "url": "/macos27/photo-8.svg",
    "takenAt": "2026-05-02T18:44:00",
    "favorite": true,
    "deleted": false,
    "edited": false,
    "w": 1600,
    "h": 1067
  }
]
