/**
 * GENERATED by scripts/sync-extracted.mjs — content extracted from the original
 * macos27 bundle. Edit /tmp/extracted/*.json + re-run the script instead of editing.
 * Source: reminders.json
 */
export const remindersSeed = {
  "lists": [
    {
      "id": "personal",
      "name": "Personal",
      "color": "#0A84FF",
      "glyph": "ListChecks"
    },
    {
      "id": "groceries",
      "name": "Groceries",
      "color": "#FF9F0A",
      "glyph": "ShoppingCart"
    },
    {
      "id": "work",
      "name": "Work",
      "color": "#30D158",
      "glyph": "Briefcase"
    }
  ],
  "reminders": [
    {
      "id": "rem-mtp61i9x-1",
      "listId": "work",
      "title": "Send brand review feedback to Maya",
      "notes": "Include the logo spacing comments.",
      "due": 1788685200000,
      "repeat": "never",
      "priority": 0,
      "tags": [],
      "flagged": true,
      "completed": false,
      "completedAt": null,
      "notified": false,
      "dueRel": {
        "dayOffset": 0,
        "time": "17:00"
      },
      "createdMinutesAgo": 1440
    },
    {
      "id": "rem-mtp61i9x-2",
      "listId": "work",
      "title": "Review PR #142 — genie animation",
      "notes": "",
      "due": 1788678000000,
      "repeat": "never",
      "priority": 1,
      "tags": [
        "code"
      ],
      "flagged": false,
      "completed": false,
      "completedAt": null,
      "notified": false,
      "dueRel": {
        "dayOffset": 0,
        "time": "15:00"
      },
      "createdMinutesAgo": 1440
    },
    {
      "id": "rem-mtp61i9x-3",
      "listId": "personal",
      "title": "Pick up dry cleaning",
      "notes": "",
      "due": 1788687000000,
      "repeat": "never",
      "priority": 0,
      "tags": [],
      "flagged": false,
      "completed": false,
      "completedAt": null,
      "notified": false,
      "dueRel": {
        "dayOffset": 0,
        "time": "17:30"
      },
      "createdMinutesAgo": 1440
    },
    {
      "id": "rem-mtp61i9x-4",
      "listId": "work",
      "title": "Prepare Q3 demo slides",
      "notes": "Demo numbers + the refraction toggle.",
      "due": 1788742800000,
      "repeat": "never",
      "priority": 2,
      "tags": [],
      "flagged": false,
      "completed": false,
      "completedAt": null,
      "notified": false,
      "dueRel": {
        "dayOffset": 1,
        "time": "09:00"
      },
      "createdMinutesAgo": 1440
    },
    {
      "id": "rem-mtp61i9x-5",
      "listId": "personal",
      "title": "Renew gym membership",
      "notes": "",
      "due": 1788840000000,
      "repeat": "never",
      "priority": 0,
      "tags": [],
      "flagged": false,
      "completed": false,
      "completedAt": null,
      "notified": false,
      "dueRel": {
        "dayOffset": 2,
        "time": "12:00"
      },
      "createdMinutesAgo": 1440
    },
    {
      "id": "rem-mtp61i9x-6",
      "listId": "personal",
      "title": "Call Mom 🌻",
      "notes": "",
      "due": 1788919200000,
      "repeat": "never",
      "priority": 0,
      "tags": [],
      "flagged": true,
      "completed": false,
      "completedAt": null,
      "notified": false,
      "dueRel": {
        "dayOffset": 3,
        "time": "10:00"
      },
      "createdMinutesAgo": 1440
    },
    {
      "id": "rem-mtp61i9x-7",
      "listId": "personal",
      "title": "Book dentist follow-up",
      "notes": "",
      "due": 1789174800000,
      "repeat": "never",
      "priority": 0,
      "tags": [],
      "flagged": false,
      "completed": false,
      "completedAt": null,
      "notified": false,
      "dueRel": {
        "dayOffset": 6,
        "time": "09:00"
      },
      "createdMinutesAgo": 1440
    },
    {
      "id": "rem-mtp61i9x-8",
      "listId": "groceries",
      "title": "Oat milk",
      "notes": "",
      "due": null,
      "repeat": "never",
      "priority": 0,
      "tags": [],
      "flagged": false,
      "completed": false,
      "completedAt": null,
      "notified": false,
      "createdMinutesAgo": 1440
    },
    {
      "id": "rem-mtp61i9x-9",
      "listId": "groceries",
      "title": "Eggs",
      "notes": "",
      "due": null,
      "repeat": "never",
      "priority": 0,
      "tags": [],
      "flagged": false,
      "completed": false,
      "completedAt": null,
      "notified": false,
      "createdMinutesAgo": 1440
    },
    {
      "id": "rem-mtp61i9x-10",
      "listId": "groceries",
      "title": "Sourdough bread",
      "notes": "",
      "due": null,
      "repeat": "never",
      "priority": 0,
      "tags": [],
      "flagged": false,
      "completed": false,
      "completedAt": null,
      "notified": false,
      "createdMinutesAgo": 1440
    },
    {
      "id": "rem-mtp61i9x-11",
      "listId": "personal",
      "title": "Water the plants",
      "notes": "",
      "due": null,
      "repeat": "never",
      "priority": 0,
      "tags": [],
      "flagged": false,
      "completed": true,
      "completedAt": 1788602400000,
      "notified": false,
      "completedAtRel": {
        "dayOffset": -1,
        "time": "18:00"
      },
      "createdMinutesAgo": 1440
    },
    {
      "id": "rem-mtp61i9x-12",
      "listId": "personal",
      "title": "Pay credit card bill",
      "notes": "",
      "due": null,
      "repeat": "never",
      "priority": 0,
      "tags": [],
      "flagged": false,
      "completed": true,
      "completedAt": 1788490800000,
      "notified": false,
      "completedAtRel": {
        "dayOffset": -2,
        "time": "11:00"
      },
      "createdMinutesAgo": 1440
    },
    {
      "id": "rem-mtp61i9x-13",
      "listId": "work",
      "title": "Submit June expense report",
      "notes": "",
      "due": null,
      "repeat": "never",
      "priority": 0,
      "tags": [],
      "flagged": false,
      "completed": true,
      "completedAt": 1788336000000,
      "notified": false,
      "completedAtRel": {
        "dayOffset": -4,
        "time": "16:00"
      },
      "createdMinutesAgo": 1440
    }
  ]
}

