/**
 * GENERATED by scripts/sync-extracted.mjs — content extracted from the original
 * macos27 bundle. Plain source file now — edit it directly; re-running sync-extracted.mjs overwrites it.
 * Source: safari.json
 */
export const bookmarksSeed = [
  {
    "id": "bm-apple",
    "title": "Apple",
    "url": "https://www.apple.com/",
    "folder": "favorites"
  },
  {
    "id": "bm-wiki",
    "title": "Wikipedia",
    "url": "https://www.wikipedia.org/",
    "folder": "favorites"
  },
  {
    "id": "bm-hn",
    "title": "Hacker News",
    "url": "https://news.ycombinator.com/",
    "folder": "favorites"
  },
  {
    "id": "bm-github",
    "title": "GitHub Trending",
    "url": "https://github.com/trending",
    "folder": "favorites"
  },
  {
    "id": "bm-liquid",
    "title": "Liquid Glass — Apple Developer",
    "url": "reader:liquid-glass",
    "folder": "menu"
  }
]
