/**
 * GENERATED by scripts/sync-extracted.mjs — content extracted from the original
 * macos27 bundle. Plain source file now — edit it directly; re-running sync-extracted.mjs overwrites it.
 * Source: music.json
 */
// Media URLs are BASE_URL-relative so dev (/macos27/), CF (/) and any base resolve.
const B = (f: string) => import.meta.env.BASE_URL + f

export const tracksSeed = [
  {
    "id": "t1",
    "title": "Neon Skyline",
    "artist": "Vector Fields",
    "album": "Neon Skyline — Single",
    "genre": "Synthwave",
    "src": B("app/src/apps/music/audio/track-1.mp3"),
    "artwork": B("images/cover-1.svg"),
    "duration": 0,
    "addedAt": "2026-07-02T10:00:00"
  },
  {
    "id": "t2",
    "title": "Golden Hour",
    "artist": "Café Mono",
    "album": "Golden Hour",
    "genre": "Lo-Fi",
    "src": B("app/src/apps/music/audio/track-2.mp3"),
    "artwork": B("images/cover-2.svg"),
    "duration": 0,
    "addedAt": "2026-07-06T10:00:00"
  },
  {
    "id": "t3",
    "title": "Blue Note Sessions",
    "artist": "The Meridian Trio",
    "album": "Blue Note Sessions",
    "genre": "Jazz",
    "src": B("app/src/apps/music/audio/track-3.mp3"),
    "artwork": B("images/cover-3.svg"),
    "duration": 0,
    "addedAt": "2026-07-10T10:00:00"
  },
  {
    "id": "t4",
    "title": "Drift",
    "artist": "Isla Wave",
    "album": "Drift",
    "genre": "Ambient",
    "src": B("app/src/apps/music/audio/track-4.mp3"),
    "artwork": B("images/cover-4.svg"),
    "duration": 0,
    "addedAt": "2026-07-14T10:00:00"
  }
]
