/**
 * GENERATED by scripts/sync-extracted.mjs — content extracted from the original
 * macos27 bundle. Edit /tmp/extracted/*.json + re-run the script instead of editing.
 * Source: music.json
 */
export const tracksSeed = [
  {
    "id": "t1",
    "title": "Neon Skyline",
    "artist": "Vector Fields",
    "album": "Neon Skyline — Single",
    "genre": "Synthwave",
    "src": "/macos27/track-1.mp3",
    "artwork": "/macos27/cover-1.svg",
    "duration": 0,
    "addedAt": "2026-07-02T10:00:00"
  },
  {
    "id": "t2",
    "title": "Golden Hour",
    "artist": "Café Mono",
    "album": "Golden Hour",
    "genre": "Lo-Fi",
    "src": "/macos27/track-2.mp3",
    "artwork": "/macos27/cover-2.svg",
    "duration": 0,
    "addedAt": "2026-07-06T10:00:00"
  },
  {
    "id": "t3",
    "title": "Blue Note Sessions",
    "artist": "The Meridian Trio",
    "album": "Blue Note Sessions",
    "genre": "Jazz",
    "src": "/macos27/track-3.mp3",
    "artwork": "/macos27/cover-3.svg",
    "duration": 0,
    "addedAt": "2026-07-10T10:00:00"
  },
  {
    "id": "t4",
    "title": "Drift",
    "artist": "Isla Wave",
    "album": "Drift",
    "genre": "Ambient",
    "src": "/macos27/track-4.mp3",
    "artwork": "/macos27/cover-4.svg",
    "duration": 0,
    "addedAt": "2026-07-14T10:00:00"
  }
]
