/**
 * GENERATED by scripts/sync-extracted.mjs — content extracted from the original
 * macos27 bundle. Edit /tmp/extracted/*.json + re-run the script instead of editing.
 * Source: calendar.json
 */
export const calendarSeed = {
  "calendars": [
    {
      "id": "personal",
      "name": "Personal",
      "color": "#30D158",
      "visible": true
    },
    {
      "id": "work",
      "name": "Work",
      "color": "#0A84FF",
      "visible": true
    },
    {
      "id": "birthdays",
      "name": "Birthdays",
      "color": "#FF9F0A",
      "visible": true
    }
  ],
  "events": [
    {
      "id": "ev-mtp61ils-1",
      "calId": "work",
      "title": "Submit timesheet",
      "location": "",
      "start": 1788598800000,
      "end": 1788600600000,
      "allDay": false,
      "repeat": "none",
      "alert": "none",
      "notes": "",
      "startRel": {
        "dayOffset": -1,
        "time": "17:00"
      },
      "endRel": {
        "dayOffset": -1,
        "time": "17:30"
      }
    },
    {
      "id": "ev-mtp61ils-2",
      "calId": "personal",
      "title": "Gym",
      "location": "",
      "start": 1788130800000,
      "end": 1788134400000,
      "allDay": false,
      "repeat": "weekly",
      "alert": "none",
      "notes": "",
      "startRel": {
        "dayOffset": -6,
        "time": "07:00"
      },
      "endRel": {
        "dayOffset": -6,
        "time": "08:00"
      }
    },
    {
      "id": "ev-mtp61ils-3",
      "calId": "personal",
      "title": "Gym",
      "location": "",
      "start": 1788303600000,
      "end": 1788307200000,
      "allDay": false,
      "repeat": "weekly",
      "alert": "none",
      "notes": "",
      "startRel": {
        "dayOffset": -4,
        "time": "07:00"
      },
      "endRel": {
        "dayOffset": -4,
        "time": "08:00"
      }
    },
    {
      "id": "ev-mtp61ils-4",
      "calId": "personal",
      "title": "Gym",
      "location": "",
      "start": 1788476400000,
      "end": 1788480000000,
      "allDay": false,
      "repeat": "weekly",
      "alert": "none",
      "notes": "",
      "startRel": {
        "dayOffset": -2,
        "time": "07:00"
      },
      "endRel": {
        "dayOffset": -2,
        "time": "08:00"
      }
    },
    {
      "id": "ev-mtp61ils-5",
      "calId": "work",
      "title": "Design review — Liquid Glass",
      "location": "Studio 2",
      "start": 1788660000000,
      "end": 1788663600000,
      "allDay": false,
      "repeat": "none",
      "alert": "10m",
      "notes": "",
      "startRel": {
        "dayOffset": 0,
        "time": "10:00"
      },
      "endRel": {
        "dayOffset": 0,
        "time": "11:00"
      }
    },
    {
      "id": "ev-mtp61ils-6",
      "calId": "work",
      "title": "1:1 with Maya",
      "location": "",
      "start": 1788674400000,
      "end": 1788676200000,
      "allDay": false,
      "repeat": "none",
      "alert": "none",
      "notes": "",
      "startRel": {
        "dayOffset": 0,
        "time": "14:00"
      },
      "endRel": {
        "dayOffset": 0,
        "time": "14:30"
      }
    },
    {
      "id": "ev-mtp61ils-7",
      "calId": "work",
      "title": "Sprint planning",
      "location": "",
      "start": 1788744600000,
      "end": 1788750000000,
      "allDay": false,
      "repeat": "none",
      "alert": "none",
      "notes": "",
      "startRel": {
        "dayOffset": 1,
        "time": "09:30"
      },
      "endRel": {
        "dayOffset": 1,
        "time": "11:00"
      }
    },
    {
      "id": "ev-mtp61ils-8",
      "calId": "personal",
      "title": "Dentist",
      "location": "",
      "start": 1788762600000,
      "end": 1788766200000,
      "allDay": false,
      "repeat": "none",
      "alert": "10m",
      "notes": "",
      "startRel": {
        "dayOffset": 1,
        "time": "14:30"
      },
      "endRel": {
        "dayOffset": 1,
        "time": "15:30"
      }
    },
    {
      "id": "ev-mtp61ils-9",
      "calId": "personal",
      "title": "Book club — Project Hail Mary",
      "location": "",
      "start": 1788861600000,
      "end": 1788867000000,
      "allDay": false,
      "repeat": "none",
      "alert": "none",
      "notes": "",
      "startRel": {
        "dayOffset": 2,
        "time": "18:00"
      },
      "endRel": {
        "dayOffset": 2,
        "time": "19:30"
      }
    },
    {
      "id": "ev-mtp61ils-10",
      "calId": "personal",
      "title": "Movie night with Alex 🎬",
      "location": "",
      "start": 1788951600000,
      "end": 1788962400000,
      "allDay": false,
      "repeat": "none",
      "alert": "none",
      "notes": "",
      "startRel": {
        "dayOffset": 3,
        "time": "19:00"
      },
      "endRel": {
        "dayOffset": 3,
        "time": "22:00"
      }
    },
    {
      "id": "ev-mtp61ils-11",
      "calId": "personal",
      "title": "Dinner with Mom & Dad",
      "location": "",
      "start": 1789036200000,
      "end": 1789043400000,
      "allDay": false,
      "repeat": "none",
      "alert": "none",
      "notes": "",
      "startRel": {
        "dayOffset": 4,
        "time": "18:30"
      },
      "endRel": {
        "dayOffset": 4,
        "time": "20:30"
      }
    },
    {
      "id": "ev-mtp61ils-12",
      "calId": "work",
      "title": "Flight to SFO — UA 1187",
      "location": "",
      "start": 1789089900000,
      "end": 1789096200000,
      "allDay": false,
      "repeat": "none",
      "alert": "none",
      "notes": "Terminal 2, seat 14A",
      "startRel": {
        "dayOffset": 5,
        "time": "09:25"
      },
      "endRel": {
        "dayOffset": 5,
        "time": "11:10"
      }
    },
    {
      "id": "ev-mtp61ils-13",
      "calId": "personal",
      "title": "Lake Tahoe weekend 🏔",
      "location": "",
      "start": 1789142400000,
      "end": 1789315200000,
      "allDay": true,
      "repeat": "none",
      "alert": "none",
      "notes": "",
      "startRel": {
        "dayOffset": 6,
        "time": "00:00"
      },
      "endRel": {
        "dayOffset": 8,
        "time": "00:00"
      }
    },
    {
      "id": "ev-mtp61ils-14",
      "calId": "birthdays",
      "title": "Priya's Birthday",
      "location": "",
      "start": 1789401600000,
      "end": 1789488000000,
      "allDay": true,
      "repeat": "none",
      "alert": "none",
      "notes": "",
      "startRel": {
        "dayOffset": 9,
        "time": "00:00"
      },
      "endRel": {
        "dayOffset": 10,
        "time": "00:00"
      }
    },
    {
      "id": "ev-mtp61ils-15",
      "calId": "birthdays",
      "title": "Mom's Birthday",
      "location": "",
      "start": 1791216000000,
      "end": 1791302400000,
      "allDay": true,
      "repeat": "none",
      "alert": "attime",
      "notes": "Linen apron? See gift ideas note.",
      "startRel": {
        "dayOffset": 30,
        "time": "00:00"
      },
      "endRel": {
        "dayOffset": 31,
        "time": "00:00"
      }
    }
  ]
}

