/**
 * GENERATED by scripts/sync-extracted.mjs — content extracted from the original
 * macos27 bundle. Edit /tmp/extracted/*.json + re-run the script instead of editing.
 * Source: stocks.json
 */
export const stocksSeed = [
  {
    "symbol": "AAPL",
    "name": "Apple Inc.",
    "price": null,
    "change": null
  },
  {
    "symbol": "MSFT",
    "name": "Microsoft Corp.",
    "price": null,
    "change": null
  },
  {
    "symbol": "NVDA",
    "name": "NVIDIA Corp.",
    "price": null,
    "change": null
  },
  {
    "symbol": "TSLA",
    "name": "Tesla, Inc.",
    "price": null,
    "change": null
  },
  {
    "symbol": "GOOG",
    "name": "Alphabet Inc.",
    "price": null,
    "change": null
  },
  {
    "symbol": "AMZN",
    "name": "Amazon.com, Inc.",
    "price": null,
    "change": null
  },
  {
    "symbol": "NFLX",
    "name": "Netflix, Inc.",
    "price": null,
    "change": null
  },
  {
    "symbol": "META",
    "name": "Meta Platforms, Inc.",
    "price": null,
    "change": null
  },
  {
    "symbol": "AMD",
    "name": "Advanced Micro Devices",
    "price": null,
    "change": null
  },
  {
    "symbol": "INTC",
    "name": "Intel Corp.",
    "price": null,
    "change": null
  },
  {
    "symbol": "DIS",
    "name": "Walt Disney Co.",
    "price": null,
    "change": null
  },
  {
    "symbol": "UBER",
    "name": "Uber Technologies",
    "price": null,
    "change": null
  },
  {
    "symbol": "SHOP",
    "name": "Shopify Inc.",
    "price": null,
    "change": null
  },
  {
    "symbol": "PLTR",
    "name": "Palantir Technologies",
    "price": null,
    "change": null
  },
  {
    "symbol": "COIN",
    "name": "Coinbase Global",
    "price": null,
    "change": null
  },
  {
    "symbol": "CRM",
    "name": "Salesforce, Inc.",
    "price": null,
    "change": null
  },
  {
    "symbol": "ORCL",
    "name": "Oracle Corp.",
    "price": null,
    "change": null
  },
  {
    "symbol": "ADBE",
    "name": "Adobe Inc.",
    "price": null,
    "change": null
  },
  {
    "symbol": "PYPL",
    "name": "PayPal Holdings",
    "price": null,
    "change": null
  },
  {
    "symbol": "SQ",
    "name": "Block, Inc.",
    "price": null,
    "change": null
  },
  {
    "symbol": "BABA",
    "name": "Alibaba Group",
    "price": null,
    "change": null
  },
  {
    "symbol": "TSM",
    "name": "TSMC (ADR)",
    "price": null,
    "change": null
  },
  {
    "symbol": "AVGO",
    "name": "Broadcom Inc.",
    "price": null,
    "change": null
  },
  {
    "symbol": "QCOM",
    "name": "Qualcomm Inc.",
    "price": null,
    "change": null
  },
  {
    "symbol": "TXN",
    "name": "Texas Instruments",
    "price": null,
    "change": null
  }
]
