/**
 * GENERATED by scripts/sync-extracted.mjs — content extracted from the original
 * macos27 bundle. Edit /tmp/extracted/*.json + re-run the script instead of editing.
 * Source: weather.json
 */
export const citiesSeed = [
  {
    "id": "tokyo",
    "name": "Tokyo",
    "country": "Japan",
    "lat": 35.676,
    "lon": 139.65
  },
  {
    "id": "london",
    "name": "London",
    "country": "United Kingdom",
    "lat": 51.507,
    "lon": -0.128
  },
  {
    "id": "fav-ggb",
    "name": "Golden Gate Bridge",
    "country": "",
    "lat": 37.8199,
    "lon": -122.4783
  },
  {
    "id": "fav-yosemite",
    "name": "Yosemite Valley",
    "country": "",
    "lat": 37.7456,
    "lon": -119.5936
  },
  {
    "id": "fav-tahoe",
    "name": "Lake Tahoe",
    "country": "",
    "lat": 39.0968,
    "lon": -120.0324
  }
]
