/**
 * GENERATED by scripts/sync-extracted.mjs — content extracted from the original
 * macos27 bundle. Edit /tmp/extracted/*.json + re-run the script instead of editing.
 * Source: video objects in bundle
 */
export const videosSeed = [
  {
    "name": "Big Buck Bunny (sample).mp4",
    "url": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "desc": "Blender Foundation — classic sample reel"
  },
  {
    "name": "Flower (CC0).mp4",
    "url": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    "desc": "MDN CC0 sample"
  },
  {
    "name": "Nature Clip.mp4",
    "url": "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    "desc": "MDN CC0 sample"
  }
]
