/**
 * GENERATED by scripts/sync-extracted.mjs — content extracted from the original
 * macos27 bundle. Plain source file now — edit it directly; re-running sync-extracted.mjs overwrites it.
 * Source: /tmp/extracted/fs-seeds.json
 */
import type { FsNode } from './stores/fs'

const min = (m: number) => Date.now() - m * 60_000
const node = (o: Omit<FsNode, 'created' | 'modified'> & { ageMin: number }): FsNode => {
  const { ageMin, ...rest } = o
  return { ...rest, created: min(ageMin), modified: min(ageMin) }
}

export const FS_SEED: FsNode[] = [
  node({ id: "root", parentId: null, name: "/", kind: "folder", ageMin: 0 }),
  node({ id: "applications", parentId: "root", name: "Applications", kind: "folder", ageMin: 0 }),
  node({ id: "apps-utilities", parentId: "applications", name: "Utilities", kind: "folder", ageMin: 0 }),
  node({ id: "users", parentId: "root", name: "Users", kind: "folder", ageMin: 0 }),
  node({ id: "home", parentId: "users", name: "oxlyn", kind: "folder", ageMin: 0 }),
  node({ id: "desktop", parentId: "home", name: "Desktop", kind: "folder", ageMin: 0 }),
  node({ id: "documents", parentId: "home", name: "Documents", kind: "folder", ageMin: 0 }),
  node({ id: "downloads", parentId: "home", name: "Downloads", kind: "folder", ageMin: 0 }),
  node({ id: "pictures", parentId: "home", name: "Pictures", kind: "folder", ageMin: 0 }),
  node({ id: "music", parentId: "home", name: "Music", kind: "folder", ageMin: 0 }),
  node({ id: "trash", parentId: "home", name: ".trash", kind: "folder", ageMin: 0 }),
  node({ id: "seed-zip", parentId: "downloads", name: "macOS27-WallpaperPack.zip", kind: "file", mime: "application/zip", ageMin: 0 }),
  node({ id: "seed-photolib", parentId: "pictures", name: "Photo Library", kind: "folder", ageMin: 0 }),
  node({ id: "seed-photo-1", parentId: "seed-photolib", name: "photo-1.svg", kind: "file", mime: "image/svg+xml", ageMin: 0 }),
  node({ id: "seed-photo-2", parentId: "seed-photolib", name: "photo-2.svg", kind: "file", mime: "image/svg+xml", ageMin: 0 }),
  node({ id: "seed-photo-3", parentId: "seed-photolib", name: "photo-3.svg", kind: "file", mime: "image/svg+xml", ageMin: 0 }),
  node({ id: "seed-photo-4", parentId: "seed-photolib", name: "photo-4.svg", kind: "file", mime: "image/svg+xml", ageMin: 0 }),
  node({ id: "seed-photo-5", parentId: "seed-photolib", name: "photo-5.svg", kind: "file", mime: "image/svg+xml", ageMin: 0 }),
  node({ id: "seed-photo-6", parentId: "seed-photolib", name: "photo-6.svg", kind: "file", mime: "image/svg+xml", ageMin: 0 }),
  node({ id: "seed-photo-7", parentId: "seed-photolib", name: "photo-7.svg", kind: "file", mime: "image/svg+xml", ageMin: 0 }),
  node({ id: "seed-photo-8", parentId: "seed-photolib", name: "photo-8.svg", kind: "file", mime: "image/svg+xml", ageMin: 0 }),
  node({ id: "seed-medialib", parentId: "music", name: "Media", kind: "folder", ageMin: 0 }),
  node({ id: "seed-track-1", parentId: "seed-medialib", name: "track-1.mp3", kind: "file", mime: "audio/mpeg", ageMin: 0 }),
  node({ id: "seed-track-2", parentId: "seed-medialib", name: "track-2.mp3", kind: "file", mime: "audio/mpeg", ageMin: 0 }),
  node({ id: "seed-track-3", parentId: "seed-medialib", name: "track-3.mp3", kind: "file", mime: "audio/mpeg", ageMin: 0 }),
  node({ id: "seed-track-4", parentId: "seed-medialib", name: "track-4.mp3", kind: "file", mime: "audio/mpeg", ageMin: 0 }),
]
