/**
 * GENERATED by scripts/sync-extracted.mjs — content extracted from the original
 * macos27 bundle. Plain source file now — edit it directly; re-running sync-extracted.mjs overwrites it.
 * Source: /tmp/extracted/notes-seeds.json
 */
import type { Note, NoteFolder } from './stores/notes'

const min = (m: number) => Date.now() - m * 60_000

export const NOTES_SEED = (): Note[] => [
  { id: 'seed-note-4', folder: "notes" as NoteFolder, html: "<h1>Recipe — Miso ramen</h1><h3>Ingredients</h3><ul><li>Miso paste</li><li>Sesame oil</li><li>Noodles</li><li>Soft egg (6:30 exactly)</li><li>Scallions</li></ul><h3>Steps</h3><ol><li>Simmer broth with miso, do not boil.</li><li>Cook noodles 3 min, drain.</li><li>Soft-boil egg 6:30, ice bath, peel.</li><li>Assemble: noodles, broth, egg, scallions, sesame drizzle.</li></ol>", tags: ["personal"], created: min(3000), modified: min(3000) },
  { id: 'seed-note-5', folder: "personal" as NoteFolder, html: "<h1>Skylar 🐾</h1><ul data-dash=\"1\"><li>Best dog (cream Lab)</li><li>Photos live in the Photos app</li><li>Walks are non-negotiable</li></ul>", tags: [], created: min(1800), modified: min(1800) },
  { id: 'seed-note-6', folder: "personal" as NoteFolder, html: "<h1>Reading — the anchors</h1><ol><li>The Outsiders — Thorndike</li><li>Poor Charlie’s Almanack — Munger</li><li>The Innovator’s Dilemma — Christensen</li><li>AI Engineering — Chip Huyen</li><li>The Almanack of Naval Ravikant</li><li>Amazon Shareholder Letters — Bezos</li></ol>", tags: [], created: min(5400), modified: min(5400) },
  { id: 'seed-note-7', folder: "travel" as NoteFolder, html: "<h1>Toronto ⇄ Boston kit</h1><ul data-cl=\"1\"><li data-checked=\"0\">Laptop + chargers</li><li data-checked=\"0\">One LeetCode problem, offline</li><li data-checked=\"0\">Podcast queue: study briefs</li><li data-checked=\"0\">Presto + CharlieCard</li><li data-checked=\"0\">Noise-cancelling headphones</li></ul>", tags: [], created: min(720), modified: min(720) },
]
