/**
 * GENERATED by scripts/sync-extracted.mjs — content extracted from the original
 * macos27 bundle. Edit /tmp/extracted/*.json + re-run the script instead of editing.
 * Source: news.json
 */
export const articlesSeed = [
  {
    "id": "liquid-glass",
    "title": "Liquid Glass: Designing for Depth",
    "source": "Apple Developer",
    "dateline": "WWDC 2026 · Human Interface Guidelines",
    "paragraphs": [
      "Liquid Glass is a new dynamic material that combines the optical properties of glass with a fluid sense of lightness. It refracts light from the content behind it, adapts its tint to the surrounding color, and brings a heightened sense of focus to controls without competing with content.",
      "The material is reserved for the floating layer of the interface: the menu bar, Dock, sidebars, toolbars, and system overlays. Content regions remain opaque so that text and imagery always keep maximum contrast and legibility.",
      "Specularity is the defining characteristic. A narrow highlight travels along the rim of each control as the pointer moves, while a subtle inner glow suggests thickness. Together they make every surface feel carved from a single sheet of glass.",
      "For developers, the guidance is simple: adopt the material for chrome, keep content solid, animate only transform and opacity, and let the system handle refraction, vibration, and accessibility fallbacks such as Reduce Transparency."
    ]
  },
  {
    "id": "verge-review",
    "title": "macOS 27 review: the glass reset",
    "source": "The Verge",
    "dateline": "July 14, 2026 · Reviews",
    "paragraphs": [
      "macOS 27 is the most opinionated desktop release Apple has shipped in a decade. Nearly every piece of chrome — the Dock, the menu bar, sidebars, even context menus — is now rendered in what Apple calls Liquid Glass, a translucent material that tints itself based on whatever sits behind it.",
      "The effect could have been a readability disaster, but it is not. Text stays on opaque surfaces, and the glass itself is tuned toward higher contrast than the betas. After a week, the transparency fades into the background and what remains is a calmer, more layered desktop.",
      "The best changes are small: windows snap with a satisfying spring, Spotlight finally feels instant, and per-window focus follows the pointer with far less surprise. Battery life on the M4 Air is effectively unchanged, which is its own kind of feature.",
      "Verdict: an easy recommendation. macOS 27 is a visual reset that respects the Mac’s decades-old muscle memory instead of fighting it."
    ]
  }
]
