/**
 * GENERATED by scripts/sync-extracted.mjs — content extracted from the original
 * macos27 bundle. Edit /tmp/extracted/*.json + re-run the script instead of editing.
 * Source: messages.json
 */
export const conversationsSeed = [
  {
    "id": "conv-maya",
    "members": [
      "maya"
    ],
    "pinned": true,
    "unread": 1,
    "hideAlerts": false,
    "messages": [
      {
        "id": "msg-0-1",
        "sender": "maya",
        "text": "Did you see the new glass spec? The refraction at the edges is *chef's kiss*",
        "at": -7200000,
        "tapbacks": [],
        "atMinutesAgo": 120
      },
      {
        "id": "msg-0-2",
        "sender": "me",
        "text": "Just implemented the displacement filter. Chromium only, sadly",
        "at": -6960000,
        "tapbacks": [],
        "readAt": -6840000,
        "atMinutesAgo": 116,
        "readAtMinutesAgo": 114
      },
      {
        "id": "msg-0-3",
        "sender": "maya",
        "text": "Ship it with the fallback, no one will know 😄",
        "at": -3600000,
        "tapbacks": [],
        "atMinutesAgo": 60
      },
      {
        "id": "msg-0-4",
        "sender": "maya",
        "text": "Review moved to Friday 10 — bring the demo!",
        "at": -480000,
        "tapbacks": [],
        "atMinutesAgo": 8
      }
    ]
  },
  {
    "id": "conv-sam",
    "members": [
      "sam"
    ],
    "pinned": false,
    "unread": 0,
    "hideAlerts": false,
    "messages": [
      {
        "id": "msg-0-5",
        "sender": "sam",
        "text": "chess minimax depth 2 is honestly enough for casual play",
        "at": -86400000,
        "tapbacks": [],
        "atMinutesAgo": 1440
      },
      {
        "id": "msg-0-6",
        "sender": "me",
        "text": "agreed, alpha-beta would be overkill",
        "at": -86220000,
        "tapbacks": [],
        "readAt": -86100000,
        "atMinutesAgo": 1437,
        "readAtMinutesAgo": 1435
      },
      {
        "id": "msg-0-7",
        "sender": "sam",
        "text": "famous last words",
        "at": -85920000,
        "tapbacks": [
          {
            "emoji": "❤️",
            "by": "me"
          }
        ],
        "atMinutesAgo": 1432
      }
    ]
  },
  {
    "id": "conv-mom",
    "members": [
      "mom"
    ],
    "pinned": true,
    "unread": 0,
    "hideAlerts": false,
    "messages": [
      {
        "id": "msg-0-8",
        "sender": "mom",
        "text": "Your father planted sunflowers again 🌻",
        "at": -86400000,
        "tapbacks": [],
        "atMinutesAgo": 1440
      },
      {
        "id": "msg-0-9",
        "sender": "me",
        "text": "pics or it didn't happen",
        "at": -86040000,
        "tapbacks": [],
        "readAt": -85860000,
        "atMinutesAgo": 1434,
        "readAtMinutesAgo": 1431
      },
      {
        "id": "msg-0-10",
        "sender": "mom",
        "text": "This weekend! Come see them. And call more 😘",
        "at": -85680000,
        "tapbacks": [],
        "atMinutesAgo": 1428
      }
    ]
  },
  {
    "id": "conv-alex",
    "members": [
      "alex"
    ],
    "pinned": false,
    "unread": 0,
    "hideAlerts": false,
    "messages": [
      {
        "id": "msg-0-11",
        "sender": "alex",
        "text": "Movie night Friday?? I heard the new sci-fi one is great",
        "at": -10800000,
        "tapbacks": [],
        "atMinutesAgo": 180
      },
      {
        "id": "msg-0-12",
        "sender": "me",
        "text": "In. 7pm?",
        "at": -10680000,
        "tapbacks": [],
        "readAt": -10560000,
        "atMinutesAgo": 178,
        "readAtMinutesAgo": 176
      },
      {
        "id": "msg-0-13",
        "sender": "alex",
        "text": "perfect, I'll bring snacks",
        "at": -10440000,
        "tapbacks": [
          {
            "emoji": "‼️",
            "by": "alex"
          }
        ],
        "atMinutesAgo": 174
      }
    ]
  },
  {
    "id": "conv-priya",
    "members": [
      "priya"
    ],
    "pinned": false,
    "unread": 0,
    "hideAlerts": false,
    "messages": [
      {
        "id": "msg-0-14",
        "sender": "priya",
        "text": "Book club pick is Project Hail Mary, no arguments",
        "at": -172800000,
        "tapbacks": [],
        "atMinutesAgo": 2880
      },
      {
        "id": "msg-0-15",
        "sender": "me",
        "text": "already 3 chapters in. so good",
        "at": -172500000,
        "tapbacks": [],
        "readAt": -172320000,
        "atMinutesAgo": 2875,
        "readAtMinutesAgo": 2872
      },
      {
        "id": "msg-0-16",
        "sender": "priya",
        "text": "Thursday 6pm, my place",
        "at": -172140000,
        "tapbacks": [],
        "atMinutesAgo": 2869
      }
    ]
  },
  {
    "id": "conv-devsquad",
    "members": [
      "maya",
      "sam",
      "jordan"
    ],
    "pinned": false,
    "unread": 1,
    "hideAlerts": false,
    "messages": [
      {
        "id": "msg-0-17",
        "sender": "jordan",
        "text": "T-3 days to launch 🚀",
        "at": -14400000,
        "tapbacks": [],
        "atMinutesAgo": 240
      },
      {
        "id": "msg-0-18",
        "sender": "sam",
        "text": "genie animation is 90% there",
        "at": -14280000,
        "tapbacks": [],
        "atMinutesAgo": 238
      },
      {
        "id": "msg-0-19",
        "sender": "maya",
        "text": "the dock bounce is SO satisfying",
        "at": -10800000,
        "tapbacks": [],
        "atMinutesAgo": 180
      },
      {
        "id": "msg-0-20",
        "sender": "me",
        "text": "shipping on Friday, let's gooo",
        "at": -7200000,
        "tapbacks": [],
        "readAt": -7020000,
        "atMinutesAgo": 120,
        "readAtMinutesAgo": 117
      },
      {
        "id": "msg-0-21",
        "sender": "sam",
        "text": "standup in 10 — someone bring the launch checklist",
        "at": -1560000,
        "tapbacks": [],
        "atMinutesAgo": 26
      }
    ]
  }
]

