/**
 * GENERATED by scripts/sync-extracted.mjs — content extracted from the original
 * macos27 bundle. Edit /tmp/extracted/*.json + re-run the script instead of editing.
 * Source: disks.json
 */
export const disksSeed = [
  {
    "id": "disk0",
    "name": "APPLE SSD AP0256Q Media",
    "device": "disk0",
    "kind": "media",
    "parent": null,
    "capacityGB": 512,
    "usedGB": 297.8,
    "role": "Physical Store",
    "color": "#8E8E93"
  },
  {
    "id": "disk1",
    "name": "Container disk1",
    "device": "disk1",
    "kind": "container",
    "parent": "disk0",
    "capacityGB": 512,
    "usedGB": 297.8,
    "role": "APFS Container",
    "color": "#636366"
  },
  {
    "id": "disk1s1",
    "name": "Macintosh HD",
    "device": "disk1s1",
    "kind": "volume",
    "parent": "disk1",
    "capacityGB": 512,
    "usedGB": 42,
    "role": "System",
    "color": "#0A84FF"
  },
  {
    "id": "disk1s2",
    "name": "Data",
    "device": "disk1s2",
    "kind": "volume",
    "parent": "disk1",
    "capacityGB": 512,
    "usedGB": 253.2,
    "role": "Data",
    "color": "#64D2FF"
  },
  {
    "id": "disk1s3",
    "name": "Preboot",
    "device": "disk1s3",
    "kind": "volume",
    "parent": "disk1",
    "capacityGB": 512,
    "usedGB": 0.5,
    "role": "Preboot",
    "color": "#BF5AF2"
  },
  {
    "id": "disk1s4",
    "name": "VM",
    "device": "disk1s4",
    "kind": "volume",
    "parent": "disk1",
    "capacityGB": 512,
    "usedGB": 2.1,
    "role": "VM",
    "color": "#FF9F0A"
  }
]
