/**
 * GENERATED by scripts/sync-extracted.mjs — content extracted from the original
 * macos27 bundle. Edit /tmp/extracted/*.json + re-run the script instead of editing.
 * Source: dictionary.json
 */
export const wordsSeed = [
  {
    "w": "apple",
    "ph": "/ˈæpəl/",
    "pos": "n.",
    "def": "the round fruit of a tree of the rose family",
    "ex": "an apple a day",
    "syn": [
      "pome"
    ],
    "origin": "Old English æppel"
  },
  {
    "w": "refraction",
    "ph": "/rɪˈfrækʃən/",
    "pos": "n.",
    "def": "the bending of light passing between media of different density",
    "ex": "the refraction at the glass edge",
    "syn": [
      "bending"
    ],
    "origin": "Latin refringere, to break"
  },
  {
    "w": "pixel",
    "ph": "/ˈpɪksəl/",
    "pos": "n.",
    "def": "the smallest addressable element of a display",
    "ex": "a single dead pixel",
    "syn": [
      "dot"
    ],
    "origin": ""
  },
  {
    "w": "cursor",
    "ph": "/ˈkɜːrsər/",
    "pos": "n.",
    "def": "a movable indicator on a screen",
    "ex": "the cursor hovered over the dock",
    "syn": [
      "pointer"
    ],
    "origin": "Latin, runner"
  },
  {
    "w": "window",
    "ph": "/ˈwɪndoʊ/",
    "pos": "n.",
    "def": "a framed area on a display; an opening in a wall",
    "ex": "drag the window",
    "syn": [
      "pane"
    ],
    "origin": "Old Norse vindauga"
  },
  {
    "w": "dock",
    "ph": "/dɑːk/",
    "pos": "n.",
    "def": "a bar of app icons; a harbor platform",
    "ex": "pinned to the dock",
    "syn": [
      "pier",
      "wharf"
    ],
    "origin": ""
  },
  {
    "w": "wallpaper",
    "ph": "/ˈwɔːlˌpeɪpər/",
    "pos": "n.",
    "def": "a decorative background image",
    "ex": "the Tahoe wallpaper",
    "syn": [
      "background"
    ],
    "origin": ""
  },
  {
    "w": "notification",
    "ph": "/ˌnoʊtɪfɪˈkeɪʃən/",
    "pos": "n.",
    "def": "an alert delivered to a user",
    "ex": "a banner notification",
    "syn": [
      "alert"
    ],
    "origin": ""
  },
  {
    "w": "system",
    "ph": "/ˈsɪstəm/",
    "pos": "n.",
    "def": "a set of connected parts forming a whole",
    "ex": "the operating system",
    "syn": [
      "structure"
    ],
    "origin": "Greek systēma"
  },
  {
    "w": "design",
    "ph": "/dɪˈzaɪn/",
    "pos": "n./v.",
    "def": "a plan, or the act of planning form and function",
    "ex": "Liquid Glass design",
    "syn": [
      "blueprint"
    ],
    "origin": "Latin designare"
  },
  {
    "w": "glass",
    "ph": "/ɡlæs/",
    "pos": "n.",
    "def": "a hard transparent material",
    "ex": "layers of glass",
    "syn": [
      "crystal"
    ],
    "origin": ""
  },
  {
    "w": "ocean",
    "ph": "/ˈoʊʃən/",
    "pos": "n.",
    "def": "the vast body of salt water",
    "ex": "the Pacific ocean",
    "syn": [
      "sea"
    ],
    "origin": ""
  },
  {
    "w": "mountain",
    "ph": "/ˈmaʊntən/",
    "pos": "n.",
    "def": "a large natural elevation of the earth’s surface",
    "ex": "Sierra mountains",
    "syn": [
      "peak"
    ],
    "origin": ""
  },
  {
    "w": "coffee",
    "ph": "/ˈkɔːfi/",
    "pos": "n.",
    "def": "a brewed drink from roasted beans",
    "ex": "morning coffee",
    "syn": [
      "espresso"
    ],
    "origin": "Arabic qahwa"
  },
  {
    "w": "music",
    "ph": "/ˈmjuːzɪk/",
    "pos": "n.",
    "def": "organized sound in time",
    "ex": "Apple Music",
    "syn": [
      "melody"
    ],
    "origin": "Greek mousikē"
  },
  {
    "w": "bridge",
    "ph": "/brɪdʒ/",
    "pos": "n.",
    "def": "a structure spanning an obstacle",
    "ex": "the Golden Gate Bridge",
    "syn": [
      "span"
    ],
    "origin": ""
  },
  {
    "w": "garden",
    "ph": "/ˈɡɑːrdən/",
    "pos": "n.",
    "def": "ground for growing plants",
    "ex": "sunflower garden",
    "syn": [
      "yard"
    ],
    "origin": ""
  },
  {
    "w": "keyboard",
    "ph": "/ˈkiːbɔːrd/",
    "pos": "n.",
    "def": "a set of keys for typing",
    "ex": "keyboard shortcuts",
    "syn": [
      "keypad"
    ],
    "origin": ""
  },
  {
    "w": "horizon",
    "ph": "/həˈraɪzən/",
    "pos": "n.",
    "def": "the line where earth meets sky",
    "ex": "sunset on the horizon",
    "syn": [
      "skyline"
    ],
    "origin": "Greek horizōn"
  },
  {
    "w": "melody",
    "ph": "/ˈmelədi/",
    "pos": "n.",
    "def": "a sequence of musical notes",
    "ex": "a haunting melody",
    "syn": [
      "tune"
    ],
    "origin": ""
  },
  {
    "w": "texture",
    "ph": "/ˈtekstʃər/",
    "pos": "n.",
    "def": "the feel or appearance of a surface",
    "ex": "grainy texture",
    "syn": [
      "grain"
    ],
    "origin": "Latin textura"
  },
  {
    "w": "velocity",
    "ph": "/vəˈlɑːsəti/",
    "pos": "n.",
    "def": "speed in a given direction",
    "ex": "scroll velocity",
    "syn": [
      "speed"
    ],
    "origin": "Latin velocitas"
  },
  {
    "w": "time",
    "ph": "/taɪm/",
    "pos": "n.",
    "def": "indefinite continued progress of existence",
    "ex": "what time is it",
    "syn": [
      "moment"
    ],
    "origin": ""
  },
  {
    "w": "read",
    "ph": "/riːd/",
    "pos": "v.",
    "def": "to interpret written language",
    "ex": "read the manual",
    "syn": [
      "peruse"
    ],
    "origin": ""
  },
  {
    "w": "write",
    "ph": "/raɪt/",
    "pos": "v.",
    "def": "to mark letters or words on a surface",
    "ex": "write a note",
    "syn": [
      "compose"
    ],
    "origin": ""
  },
  {
    "w": "sparkle",
    "ph": "/ˈspɑːrkəl/",
    "pos": "v./n.",
    "def": "to shine with flashes of light",
    "ex": "the specular sparkle",
    "syn": [
      "glitter",
      "shimmer"
    ],
    "origin": ""
  },
  {
    "w": "tahoe",
    "ph": "/ˈtɑːhoʊ/",
    "pos": "n.",
    "def": "a large freshwater lake in the Sierra Nevada",
    "ex": "Lake Tahoe at dawn",
    "syn": [],
    "origin": "Washo da’aw"
  }
]
