/**
 * GENERATED by scripts/sync-extracted.mjs — content extracted from the original
 * macos27 bundle. Plain source file now — edit it directly; re-running sync-extracted.mjs overwrites it.
 * Source: mail.json
 */
export const mailSeed = [
  {
    "id": "mail-0-1",
    "account": "icloud",
    "to": [
      {
        "name": "oxlyn",
        "email": "oxlyn@icloud.com"
      }
    ],
    "flagged": false,
    "mailbox": "inbox",
    "read": true,
    "from": {
      "name": "Apple",
      "email": "no-reply@apple.com"
    },
    "subject": "Your receipt from the App Store",
    "at": -1200000,
    "body": "Dear Oxlyn,\n\nThank you for your purchase. This is your receipt for Procreate ($12.99), purchased on July 16, 2026.\n\nOrder ID: MGD82K41\nBilled to: Visa ••4242\nApple ID: oxlyn@icloud.com\n\nIf you didn't authorize this purchase, visit Report a Problem at reportaproblem.apple.com within 90 days.\n\nApple\nOne Apple Park Way, Cupertino, CA 95014",
    "atMinutesAgo": 20
  },
  {
    "id": "mail-0-4",
    "account": "icloud",
    "to": [
      {
        "name": "oxlyn",
        "email": "oxlyn@icloud.com"
      }
    ],
    "flagged": true,
    "mailbox": "inbox",
    "read": false,
    "from": {
      "name": "United Airlines",
      "email": "unitedairlines@united.com"
    },
    "subject": "Your trip to Boston is coming up",
    "at": -14400000,
    "body": "Get ready for your trip, Oxlyn.\n\nSunday, July 21\nYYZ Toronto → BOS Boston\nSeat 14A · Confirmation: XK7Q2R\n\nCheck-in opens 24 hours before departure. Carry-on and one personal item are included in your fare.\n\nSee you on board.",
    "atMinutesAgo": 240
  },
  {
    "id": "mail-0-5",
    "account": "icloud",
    "to": [
      {
        "name": "oxlyn",
        "email": "oxlyn@icloud.com"
      }
    ],
    "flagged": false,
    "mailbox": "inbox",
    "read": true,
    "from": {
      "name": "Linda Harper",
      "email": "linda.harper@familymail.com"
    },
    "subject": "Photos from the garden 🌻",
    "at": -86400000,
    "body": "Hi sweetheart,\n\nThe sunflowers are taller than your father now — I measured! Attaching a few photos from this morning, the light was perfect.\n\nCome this weekend — I'll make the peach cobbler. Bring that fancy camera of yours.\n\nLove, Mom",
    "atMinutesAgo": 1440
  },
  {
    "id": "mail-0-8",
    "account": "icloud",
    "to": [
      {
        "name": "oxlyn",
        "email": "oxlyn@icloud.com"
      }
    ],
    "flagged": true,
    "mailbox": "inbox",
    "read": true,
    "from": {
      "name": "Bank of America",
      "email": "alerts@bankofamerica.com"
    },
    "subject": "Your July statement is ready",
    "at": -172800000,
    "body": "Your statement for account ••8821 is now available.\n\nStatement balance: $4,218.44\nMinimum payment due: $35.00 by August 2\n\nSign in to view the full statement and recent transactions. If you don't recognize an account listed, call the number on the back of your card.",
    "atMinutesAgo": 2880
  },
  {
    "id": "mail-0-9",
    "account": "icloud",
    "to": [
      {
        "name": "oxlyn",
        "email": "oxlyn@icloud.com"
      }
    ],
    "flagged": false,
    "mailbox": "inbox",
    "read": true,
    "from": {
      "name": "Airbnb",
      "email": "automated@airbnb.com"
    },
    "subject": "Your stay in Lake Tahoe is confirmed",
    "at": -172800000,
    "body": "You're all set, Oxlyn!\n\nCheck-in: Friday, July 25 at 4:00 PM\n891 Granite Ridge Rd, South Lake Tahoe\nHosted by Susan · Superhost\n\nThe door code will be sent 24 hours before check-in. Trails behind the cabin connect to the Granite Ridge loop — pack layers, evenings drop into the 50s.",
    "atMinutesAgo": 2880
  },
  {
    "id": "mail-0-10",
    "account": "icloud",
    "to": [
      {
        "name": "oxlyn",
        "email": "oxlyn@icloud.com"
      }
    ],
    "flagged": false,
    "mailbox": "inbox",
    "read": true,
    "from": {
      "name": "Sam Okafor",
      "email": "sam.okafor@devmail.net"
    },
    "subject": "Re: chess.js depth — benchmarks",
    "at": -259200000,
    "body": "Numbers are in:\n\ndepth 2 = ~4ms/move, depth 3 = ~90ms. depth 2 it is — casual players will never notice, and the UI stays at 60fps.\n\nAlso found a bug in my castling rights logic while I was in there. Classic.\n\n— Sam",
    "atMinutesAgo": 4320
  },
  {
    "id": "mail-0-11",
    "account": "icloud",
    "to": [
      {
        "name": "Maya Chen",
        "email": "maya.chen@designco.io"
      }
    ],
    "flagged": false,
    "mailbox": "sent",
    "read": true,
    "from": {
      "name": "oxlyn",
      "email": "oxlyn@icloud.com"
    },
    "subject": "Re: Q3 brand refresh — review Friday?",
    "at": -120000,
    "body": "Friday 10:00 works — I'll have the demo running on both Chromium and Safari so we can compare the fallback side by side.\n\nBringing popcorn.",
    "atMinutesAgo": 2
  },
  {
    "id": "mail-0-12",
    "account": "icloud",
    "to": [
      {
        "name": "Alex Rivera",
        "email": "alex.r@mailpost.io"
      }
    ],
    "flagged": false,
    "mailbox": "sent",
    "read": true,
    "from": {
      "name": "oxlyn",
      "email": "oxlyn@icloud.com"
    },
    "subject": "Itinerary for Tahoe",
    "at": -93600000,
    "body": "Cabin is booked — 891 Granite Ridge Rd, check-in Friday 4 PM. Door code comes Thursday.\n\nI'll drive. You bring snacks and the offline maps like last time.",
    "atMinutesAgo": 1560
  },
  {
    "id": "mail-0-13",
    "account": "icloud",
    "to": [],
    "flagged": false,
    "mailbox": "drafts",
    "read": true,
    "from": {
      "name": "oxlyn",
      "email": "oxlyn@icloud.com"
    },
    "subject": "Ideas for the launch post —",
    "at": -21600000,
    "body": "Working title: \"Shipping glass: how we faked physics at 60fps\"\n\n- the displacement-map trick (and the Safari fallback)\n- why the dock bounce is a cosine, not a spring\n- genie: clip-path trapezoids in 500ms\n\nTODO: screenshots, numbers from the perf pass",
    "atMinutesAgo": 360
  },
  {
    "id": "mail-0-14",
    "account": "icloud",
    "to": [
      {
        "name": "oxlyn",
        "email": "oxlyn@icloud.com"
      }
    ],
    "flagged": false,
    "mailbox": "junk",
    "read": true,
    "from": {
      "name": "Prize Notification Center",
      "email": "winner@totally-legit-prizes.biz"
    },
    "subject": "CONGRATULATIONS, you have been selected!!!",
    "at": -86400000,
    "body": "DEAR WINNER,\n\nYour email address was selected in our INTERNATIONAL E-LOTTERY. You have won $2,500,000 USD!!!\n\nTo claim your prize, reply with your full name, address, and bank details within 48 HOURS.\n\nMr. Wealth Trust\nClaims Agent",
    "atMinutesAgo": 1440
  },
  {
    "id": "mail-0-15",
    "account": "icloud",
    "to": [
      {
        "name": "oxlyn",
        "email": "oxlyn@icloud.com"
      }
    ],
    "flagged": false,
    "mailbox": "archive",
    "read": true,
    "from": {
      "name": "Apple",
      "email": "no-reply@apple.com"
    },
    "subject": "Your receipt from Apple Services",
    "at": -518400000,
    "body": "Dear Oxlyn,\n\nThis is your receipt for iCloud+ 200GB ($2.99/month), renewing July 10, 2026.\n\nBilled to: Visa ••4242\n\nManage your subscription in Settings › Apple Account.",
    "atMinutesAgo": 8640
  }
]
