/**
 * GENERATED by scripts/sync-extracted.mjs — content extracted from the original
 * macos27 bundle. Edit /tmp/extracted/*.json + re-run the script instead of editing.
 * Source: mail.json
 */
export const mailSeed = [
  {
    "id": "mail-0-1",
    "account": "icloud",
    "to": [
      {
        "name": "oxlyn",
        "email": "wilson1.wu@gmail.com"
      }
    ],
    "flagged": false,
    "mailbox": "inbox",
    "read": true,
    "from": {
      "name": "Apple",
      "email": "no-reply@apple.com"
    },
    "subject": "Your receipt from the App Store",
    "at": -1200000,
    "body": "Dear Oxlyn,\n\nThank you for your purchase. This is your receipt for Procreate ($12.99), purchased on July 16, 2026.\n\nOrder ID: MGD82K41\nBilled to: Visa ••4242\nApple ID: wilson1.wu@gmail.com\n\nIf you didn't authorize this purchase, visit Report a Problem at reportaproblem.apple.com within 90 days.\n\nApple\nOne Apple Park Way, Cupertino, CA 95014",
    "atMinutesAgo": 20
  },
  {
    "id": "mail-0-2",
    "account": "icloud",
    "to": [
      {
        "name": "oxlyn",
        "email": "wilson1.wu@gmail.com"
      }
    ],
    "flagged": false,
    "mailbox": "inbox",
    "read": false,
    "from": {
      "name": "Oxlyn",
      "email": "oxlyn@dubbscapital.com"
    },
    "subject": "Start here — about this inbox",
    "at": -480000,
    "body": "Hi — Oxlyn here. This inbox is part of the resume.\n\nWorth opening:\n• “[basenotes] Cross-device queue shipped” — a real engineering story\n• “AI Engineer Track — this week” — how I train\n• “GTM memo — how Snappy sells” — how I think about revenue\n\nThe short version: I operate three ventures (Dubbs Capital, Snappy, Union Made Apparel) and I’m building toward AI engineering — agents, RAG, evaluation, shipped for real customers.\n\nReal contact: wilson1.wu@gmail.com · (416) 412-1927 · github.com/wilsonwu-ai · linkedin.com/in/wilson1wu\n\n— Oxlyn",
    "atMinutesAgo": 8
  },
  {
    "id": "mail-0-3",
    "account": "icloud",
    "to": [
      {
        "name": "oxlyn",
        "email": "wilson1.wu@gmail.com"
      }
    ],
    "flagged": false,
    "mailbox": "inbox",
    "read": false,
    "from": {
      "name": "GitHub",
      "email": "notifications@github.com"
    },
    "subject": "[basenotes] Cross-device queue shipped — the debugging story",
    "at": -7200000,
    "body": "Shipped: cross-device queue, end to end.\n\nShopify App Proxy (HMAC-signed) → Cloudflare Worker → customer metafield → theme JS sync. A storefront-only feature got cross-device persistence without a full app build.\n\nThe debugging story is the resume-worthy part: the original “OAuth is structurally broken” conclusion was wrong. Root cause was clipboard %20 corruption inserting URL-encoded spaces into the client_id, then browser autofill polluting retries. Reading the error string literally — “api_key 92 5294…” with the space — was the giveaway.\n\nPattern banked. Auth reasoning across systems is half of real integration work.",
    "atMinutesAgo": 120
  },
  {
    "id": "mail-0-4",
    "account": "icloud",
    "to": [
      {
        "name": "oxlyn",
        "email": "wilson1.wu@gmail.com"
      }
    ],
    "flagged": true,
    "mailbox": "inbox",
    "read": false,
    "from": {
      "name": "United Airlines",
      "email": "unitedairlines@united.com"
    },
    "subject": "Your trip to Boston is coming up",
    "at": -14400000,
    "body": "Get ready for your trip, Oxlyn.\n\nSunday, July 21\nYYZ Toronto → BOS Boston\nSeat 14A · Confirmation: XK7Q2R\n\nCheck-in opens 24 hours before departure. Carry-on and one personal item are included in your fare.\n\nSee you on board.",
    "atMinutesAgo": 240
  },
  {
    "id": "mail-0-5",
    "account": "icloud",
    "to": [
      {
        "name": "oxlyn",
        "email": "wilson1.wu@gmail.com"
      }
    ],
    "flagged": false,
    "mailbox": "inbox",
    "read": true,
    "from": {
      "name": "Linda Harper",
      "email": "linda.harper@familymail.com"
    },
    "subject": "Photos from the garden 🌻",
    "at": -86400000,
    "body": "Hi sweetheart,\n\nThe sunflowers are taller than your father now — I measured! Attaching a few photos from this morning, the light was perfect.\n\nCome this weekend — I'll make the peach cobbler. Bring that fancy camera of yours.\n\nLove, Mom",
    "atMinutesAgo": 1440
  },
  {
    "id": "mail-0-6",
    "account": "icloud",
    "to": [
      {
        "name": "oxlyn",
        "email": "wilson1.wu@gmail.com"
      }
    ],
    "flagged": false,
    "mailbox": "inbox",
    "read": false,
    "from": {
      "name": "Linear",
      "email": "notifications@linear.app"
    },
    "subject": "AI Engineer Track — this week",
    "at": -86400000,
    "body": "WW-26 · AI Engineer Track — weekly focus\nPriority: High · Recurring\nProject: Operator → AI Engineer\n\n• One LeetCode problem a day — log the pattern\n• OMSCS Fall prep: Artificial Intelligence (CS 6601) + Software Development Process (CS 6300)\n• GCP Associate Cloud Engineer → Professional ML Engineer\n• Chip Huyen re-read with teach-backs — depth over velocity\n\nSlow is fast. Attempted and logged beats perfect and skipped.",
    "atMinutesAgo": 1440
  },
  {
    "id": "mail-0-7",
    "account": "icloud",
    "to": [
      {
        "name": "oxlyn",
        "email": "wilson1.wu@gmail.com"
      }
    ],
    "flagged": false,
    "mailbox": "inbox",
    "read": true,
    "from": {
      "name": "Oxlyn (Snappy)",
      "email": "oxlyn@gosnappy.io"
    },
    "subject": "GTM memo — how Snappy sells",
    "at": -86400000,
    "body": "How Snappy sells — the memo.\n\nThe buyer: an independent restaurant owner. Low attention, allergic to platform pitches, and rightly skeptical of anything that asks them to change how they operate.\n\nThe chain:\n1. WEDGE — lead with a single-visit yes. A gift-card program. A waitlist QR poster. Small, concrete, obviously useful — no operational change required.\n2. TRUST — deliver it fast and store-specific. The wedge earns two things a cold platform pitch never gets: the relationship, and the store-level context (their menu, their brand, their guests).\n3. EXPAND — the presentation-studio sell rides on that earned context. By then it is not a vendor pitch; it is the next obvious step.\n\nThe operating layer underneath: follow-up staged by deal stage in the CRM — every open deal carries a next-step date or it surfaces as an exception. And AI collapses production time: proposals and store-specific creative ship the same day they are promised, which changes deal velocity more than any script does.\n\n— Oxlyn",
    "atMinutesAgo": 1440
  },
  {
    "id": "mail-0-8",
    "account": "icloud",
    "to": [
      {
        "name": "oxlyn",
        "email": "wilson1.wu@gmail.com"
      }
    ],
    "flagged": true,
    "mailbox": "inbox",
    "read": true,
    "from": {
      "name": "Bank of America",
      "email": "alerts@bankofamerica.com"
    },
    "subject": "Your July statement is ready",
    "at": -172800000,
    "body": "Your statement for account ••8821 is now available.\n\nStatement balance: $4,218.44\nMinimum payment due: $35.00 by August 2\n\nSign in to view the full statement and recent transactions. If you don't recognize an account listed, call the number on the back of your card.",
    "atMinutesAgo": 2880
  },
  {
    "id": "mail-0-9",
    "account": "icloud",
    "to": [
      {
        "name": "oxlyn",
        "email": "wilson1.wu@gmail.com"
      }
    ],
    "flagged": false,
    "mailbox": "inbox",
    "read": true,
    "from": {
      "name": "Airbnb",
      "email": "automated@airbnb.com"
    },
    "subject": "Your stay in Lake Tahoe is confirmed",
    "at": -172800000,
    "body": "You're all set, Oxlyn!\n\nCheck-in: Friday, July 25 at 4:00 PM\n891 Granite Ridge Rd, South Lake Tahoe\nHosted by Susan · Superhost\n\nThe door code will be sent 24 hours before check-in. Trails behind the cabin connect to the Granite Ridge loop — pack layers, evenings drop into the 50s.",
    "atMinutesAgo": 2880
  },
  {
    "id": "mail-0-10",
    "account": "icloud",
    "to": [
      {
        "name": "oxlyn",
        "email": "wilson1.wu@gmail.com"
      }
    ],
    "flagged": false,
    "mailbox": "inbox",
    "read": true,
    "from": {
      "name": "Sam Okafor",
      "email": "sam.okafor@devmail.net"
    },
    "subject": "Re: chess.js depth — benchmarks",
    "at": -259200000,
    "body": "Numbers are in:\n\ndepth 2 = ~4ms/move, depth 3 = ~90ms. depth 2 it is — casual players will never notice, and the UI stays at 60fps.\n\nAlso found a bug in my castling rights logic while I was in there. Classic.\n\n— Sam",
    "atMinutesAgo": 4320
  },
  {
    "id": "mail-0-11",
    "account": "icloud",
    "to": [
      {
        "name": "Maya Chen",
        "email": "maya.chen@designco.io"
      }
    ],
    "flagged": false,
    "mailbox": "sent",
    "read": true,
    "from": {
      "name": "oxlyn",
      "email": "wilson1.wu@gmail.com"
    },
    "subject": "Re: Q3 brand refresh — review Friday?",
    "at": -120000,
    "body": "Friday 10:00 works — I'll have the demo running on both Chromium and Safari so we can compare the fallback side by side.\n\nBringing popcorn.",
    "atMinutesAgo": 2
  },
  {
    "id": "mail-0-12",
    "account": "icloud",
    "to": [
      {
        "name": "Alex Rivera",
        "email": "alex.r@mailpost.io"
      }
    ],
    "flagged": false,
    "mailbox": "sent",
    "read": true,
    "from": {
      "name": "oxlyn",
      "email": "wilson1.wu@gmail.com"
    },
    "subject": "Itinerary for Tahoe",
    "at": -93600000,
    "body": "Cabin is booked — 891 Granite Ridge Rd, check-in Friday 4 PM. Door code comes Thursday.\n\nI'll drive. You bring snacks and the offline maps like last time.",
    "atMinutesAgo": 1560
  },
  {
    "id": "mail-0-13",
    "account": "icloud",
    "to": [],
    "flagged": false,
    "mailbox": "drafts",
    "read": true,
    "from": {
      "name": "oxlyn",
      "email": "wilson1.wu@gmail.com"
    },
    "subject": "Ideas for the launch post —",
    "at": -21600000,
    "body": "Working title: \"Shipping glass: how we faked physics at 60fps\"\n\n- the displacement-map trick (and the Safari fallback)\n- why the dock bounce is a cosine, not a spring\n- genie: clip-path trapezoids in 500ms\n\nTODO: screenshots, numbers from the perf pass",
    "atMinutesAgo": 360
  },
  {
    "id": "mail-0-14",
    "account": "icloud",
    "to": [
      {
        "name": "oxlyn",
        "email": "wilson1.wu@gmail.com"
      }
    ],
    "flagged": false,
    "mailbox": "junk",
    "read": true,
    "from": {
      "name": "Prize Notification Center",
      "email": "winner@totally-legit-prizes.biz"
    },
    "subject": "CONGRATULATIONS, you have been selected!!!",
    "at": -86400000,
    "body": "DEAR WINNER,\n\nYour email address was selected in our INTERNATIONAL E-LOTTERY. You have won $2,500,000 USD!!!\n\nTo claim your prize, reply with your full name, address, and bank details within 48 HOURS.\n\nMr. Wealth Trust\nClaims Agent",
    "atMinutesAgo": 1440
  },
  {
    "id": "mail-0-15",
    "account": "icloud",
    "to": [
      {
        "name": "oxlyn",
        "email": "wilson1.wu@gmail.com"
      }
    ],
    "flagged": false,
    "mailbox": "archive",
    "read": true,
    "from": {
      "name": "Apple",
      "email": "no-reply@apple.com"
    },
    "subject": "Your receipt from Apple Services",
    "at": -518400000,
    "body": "Dear Oxlyn,\n\nThis is your receipt for iCloud+ 200GB ($2.99/month), renewing July 10, 2026.\n\nBilled to: Visa ••4242\n\nManage your subscription in Settings › Apple Account.",
    "atMinutesAgo": 8640
  }
]

